spring.application.name=query-api-service
# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/stackpulse
spring.datasource.username=postgres
spring.datasource.password=password
# Schema Management belongs to Scraper Service
spring.flyway.enabled=false
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
server.port=8081