spring.application.name=query-api-service
server.port=8081
# Database
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/stackpulse}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
# Flyway disabled - schema owned by scraper-service
spring.flyway.enabled=false
# Eureka
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
# Suppressing irrelevant errors
spring.jpa.open-in-view=false