spring.application.name=query-api-service

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/stackpulse
spring.datasource.username=postgres
spring.datasource.password=password

# Schema Management belongs to Scraper Service
spring.flyway.enabled=false