services:
  postgres:
    image: postgres:16
    container_name: stackpulse-db
    environment:
      POSTGRES_DB: stackpulse
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
