spring.application.name=api-gateway
server.port=8080
spring.cloud.gateway.routes[0].id=query-api
spring.cloud.gateway.routes[0].uri=lb://query-api-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/keywords/**
spring.main.allow-bean-definition-overriding=true
# Eureka
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka/}