INSERT INTO known_keywords (keyword, aliases, category) VALUES
-- Languages
('java', ARRAY['java 8', 'java 11', 'java 17', 'java 21'], 'language'),
('python', ARRAY['python3', 'python 3'], 'language'),
('kotlin', ARRAY[]::TEXT[], 'language'),
('scala', ARRAY[]::TEXT[], 'language'),
('go', ARRAY['golang'], 'language'),
('rust', ARRAY[]::TEXT[], 'language'),
('c#', ARRAY['csharp', 'c sharp'], 'language'),
('typescript', ARRAY['ts'], 'language'),
('javascript', ARRAY['js', 'es6', 'es2015'], 'language'),
('sql', ARRAY[]::TEXT[], 'language'),

-- Frameworks
('spring boot', ARRAY['springboot', 'spring-boot'], 'framework'),
('spring framework', ARRAY['spring core', 'spring'], 'framework'),
('spring cloud', ARRAY[]::TEXT[], 'framework'),
('spring security', ARRAY[]::TEXT[], 'framework'),
('spring data', ARRAY[]::TEXT[], 'framework'),
('hibernate', ARRAY[]::TEXT[], 'framework'),
('jpa', ARRAY['java persistence api'], 'framework'),
('node.js', ARRAY['nodejs', 'node'], 'framework'),
('django', ARRAY[]::TEXT[], 'framework'),
('fastapi', ARRAY[]::TEXT[], 'framework'),
('.net', ARRAY['dotnet', 'asp.net'], 'framework'),
('react', ARRAY['react.js', 'reactjs'], 'framework'),
('angular', ARRAY[]::TEXT[], 'framework'),
('vue', ARRAY['vue.js', 'vuejs'], 'framework'),
('micronaut', ARRAY[]::TEXT[], 'framework'),
('quarkus', ARRAY[]::TEXT[], 'framework'),

-- Databases
('postgresql', ARRAY['postgres', 'psql'], 'database'),
('mysql', ARRAY[]::TEXT[], 'database'),
('mongodb', ARRAY['mongo'], 'database'),
('redis', ARRAY[]::TEXT[], 'database'),
('cassandra', ARRAY['apache cassandra'], 'database'),
('elasticsearch', ARRAY['elastic search', 'opensearch'], 'database'),
('dynamodb', ARRAY['dynamo db', 'dynamo'], 'database'),
('oracle', ARRAY['oracle db', 'oracle database'], 'database'),
('sql server', ARRAY['mssql', 'microsoft sql server'], 'database'),
('h2', ARRAY[]::TEXT[], 'database'),

-- Cloud
('aws', ARRAY['amazon web services'], 'cloud'),
('gcp', ARRAY['google cloud', 'google cloud platform'], 'cloud'),
('azure', ARRAY['microsoft azure'], 'cloud'),
('ec2', ARRAY[]::TEXT[], 'cloud'),
('s3', ARRAY['amazon s3'], 'cloud'),
('lambda', ARRAY['aws lambda'], 'cloud'),
('eks', ARRAY['elastic kubernetes service'], 'cloud'),
('ecs', ARRAY['elastic container service'], 'cloud'),
('rds', ARRAY['amazon rds'], 'cloud'),

-- Tools
('docker', ARRAY['docker compose', 'dockerfile'], 'tool'),
('kubernetes', ARRAY['k8s'], 'tool'),
('terraform', ARRAY[]::TEXT[], 'tool'),
('jenkins', ARRAY[]::TEXT[], 'tool'),
('github actions', ARRAY['gh actions'], 'tool'),
('gitlab ci', ARRAY['gitlab ci/cd'], 'tool'),
('maven', ARRAY['apache maven'], 'tool'),
('gradle', ARRAY[]::TEXT[], 'tool'),
('git', ARRAY[]::TEXT[], 'tool'),
('jira', ARRAY[]::TEXT[], 'tool'),
('sonarqube', ARRAY['sonar'], 'tool'),
('ansible', ARRAY[]::TEXT[], 'tool'),
('helm', ARRAY[]::TEXT[], 'tool'),

-- Messaging
('kafka', ARRAY['apache kafka'], 'messaging'),
('rabbitmq', ARRAY['rabbit mq'], 'messaging'),
('activemq', ARRAY['active mq'], 'messaging'),
('sqs', ARRAY['amazon sqs'], 'messaging'),
('sns', ARRAY['amazon sns'], 'messaging'),

-- Concepts
('rest', ARRAY['restful', 'rest api', 'restful api'], 'concept'),
('graphql', ARRAY[]::TEXT[], 'concept'),
('grpc', ARRAY[]::TEXT[], 'concept'),
('microservices', ARRAY['microservice architecture'], 'concept'),
('ci/cd', ARRAY['ci cd', 'continuous integration', 'continuous deployment'], 'concept'),
('oauth', ARRAY['oauth2', 'oauth 2.0'], 'concept'),
('jwt', ARRAY['json web token'], 'concept'),
('tdd', ARRAY['test driven development'], 'concept'),
('agile', ARRAY['scrum', 'kanban'], 'concept'),
('devops', ARRAY[]::TEXT[], 'concept'),
('system design', ARRAY[]::TEXT[], 'concept'),
('multithreading', ARRAY['concurrency', 'multi-threading'], 'concept'),
('caching', ARRAY[]::TEXT[], 'concept'),
('message queue', ARRAY['message queuing'], 'concept'),
('event driven', ARRAY['event-driven', 'event driven architecture'], 'concept'),

-- Testing
('junit', ARRAY['junit 5', 'junit5'], 'testing'),
('mockito', ARRAY[]::TEXT[], 'testing'),
('selenium', ARRAY[]::TEXT[], 'testing'),
('testcontainers', ARRAY[]::TEXT[], 'testing'),
('jest', ARRAY[]::TEXT[], 'testing');