-- V3__expand_known_keywords.sql

INSERT INTO known_keywords (keyword, aliases, category) VALUES

-- Languages
('ruby', ARRAY[]::TEXT[], 'language'),
('php', ARRAY[]::TEXT[], 'language'),
('swift', ARRAY[]::TEXT[], 'language'),
('c++', ARRAY['cpp'], 'language'),
('c', ARRAY[]::TEXT[], 'language'),
('bash', ARRAY['shell', 'shell scripting'], 'language'),
('r', ARRAY[]::TEXT[], 'language'),
('dart', ARRAY[]::TEXT[], 'language'),
('elixir', ARRAY[]::TEXT[], 'language'),
('groovy', ARRAY[]::TEXT[], 'language'),

-- Frameworks
('express', ARRAY['express.js', 'expressjs'], 'framework'),
('flask', ARRAY[]::TEXT[], 'framework'),
('rails', ARRAY['ruby on rails', 'ror'], 'framework'),
('nextjs', ARRAY['next.js', 'next'], 'framework'),
('nestjs', ARRAY['nest.js'], 'framework'),
('svelte', ARRAY['svelte.js'], 'framework'),
('flutter', ARRAY[]::TEXT[], 'framework'),
('rxjava', ARRAY['rx java'], 'framework'),
('lombok', ARRAY[]::TEXT[], 'framework'),

-- Databases
('sqlite', ARRAY[]::TEXT[], 'database'),
('neo4j', ARRAY[]::TEXT[], 'database'),
('clickhouse', ARRAY[]::TEXT[], 'database'),
('snowflake', ARRAY[]::TEXT[], 'database'),
('bigquery', ARRAY['google bigquery'], 'database'),
('firebase', ARRAY['firestore'], 'database'),
('supabase', ARRAY[]::TEXT[], 'database'),
('cockroachdb', ARRAY['cockroach db'], 'database'),

-- Cloud
('cloudformation', ARRAY['aws cloudformation'], 'cloud'),
('cloudwatch', ARRAY['aws cloudwatch'], 'cloud'),
('api gateway', ARRAY['aws api gateway'], 'cloud'),
('route 53', ARRAY['route53'], 'cloud'),
('iam', ARRAY['aws iam'], 'cloud'),
('azure devops', ARRAY[]::TEXT[], 'cloud'),
('google kubernetes engine', ARRAY['gke'], 'cloud'),
('cloud run', ARRAY['google cloud run'], 'cloud'),
('vercel', ARRAY[]::TEXT[], 'cloud'),
('heroku', ARRAY[]::TEXT[], 'cloud'),
('railway', ARRAY[]::TEXT[], 'cloud'),
('digitalocean', ARRAY['digital ocean'], 'cloud'),

-- Tools
('webpack', ARRAY[]::TEXT[], 'tool'),
('vite', ARRAY[]::TEXT[], 'tool'),
('npm', ARRAY[]::TEXT[], 'tool'),
('yarn', ARRAY[]::TEXT[], 'tool'),
('postman', ARRAY[]::TEXT[], 'tool'),
('swagger', ARRAY['openapi', 'open api'], 'tool'),
('nginx', ARRAY[]::TEXT[], 'tool'),
('linux', ARRAY['unix'], 'tool'),
('confluence', ARRAY[]::TEXT[], 'tool'),
('figma', ARRAY[]::TEXT[], 'tool'),
('artifactory', ARRAY[]::TEXT[], 'tool'),
('circleci', ARRAY['circle ci'], 'tool'),
('argocd', ARRAY['argo cd'], 'tool'),
('prometheus', ARRAY[]::TEXT[], 'tool'),
('grafana', ARRAY[]::TEXT[], 'tool'),
('datadog', ARRAY[]::TEXT[], 'tool'),
('splunk', ARRAY[]::TEXT[], 'tool'),
('new relic', ARRAY['newrelic'], 'tool'),
('kibana', ARRAY[]::TEXT[], 'tool'),
('logstash', ARRAY[]::TEXT[], 'tool'),
('vault', ARRAY['hashicorp vault'], 'tool'),

-- Messaging
('pubsub', ARRAY['google pubsub', 'google pub/sub'], 'messaging'),
('nats', ARRAY[]::TEXT[], 'messaging'),
('zeromq', ARRAY['zmq'], 'messaging'),
('eventbridge', ARRAY['aws eventbridge'], 'messaging'),

-- Concepts
('domain driven design', ARRAY['ddd', 'domain-driven design'], 'concept'),
('clean architecture', ARRAY[]::TEXT[], 'concept'),
('solid', ARRAY['solid principles'], 'concept'),
('design patterns', ARRAY[]::TEXT[], 'concept'),
('api design', ARRAY[]::TEXT[], 'concept'),
('websockets', ARRAY['web sockets', 'websocket'], 'concept'),
('serverless', ARRAY[]::TEXT[], 'concept'),
('service mesh', ARRAY[]::TEXT[], 'concept'),
('soa', ARRAY['service oriented architecture'], 'concept'),
('load balancing', ARRAY['load balancer'], 'concept'),
('distributed systems', ARRAY['distributed computing'], 'concept'),
('observability', ARRAY[]::TEXT[], 'concept'),
('high availability', ARRAY['ha'], 'concept'),
('data structures', ARRAY[]::TEXT[], 'concept'),
('algorithms', ARRAY[]::TEXT[], 'concept'),
('object oriented programming', ARRAY['oop', 'object-oriented'], 'concept'),
('functional programming', ARRAY[]::TEXT[], 'concept'),
('saml', ARRAY[]::TEXT[], 'concept'),
('openid connect', ARRAY['oidc'], 'concept'),

-- Testing
('pytest', ARRAY[]::TEXT[], 'testing'),
('cypress', ARRAY[]::TEXT[], 'testing'),
('playwright', ARRAY[]::TEXT[], 'testing'),
('cucumber', ARRAY[]::TEXT[], 'testing'),
('gatling', ARRAY[]::TEXT[], 'testing'),
('jmeter', ARRAY['apache jmeter'], 'testing'),
('wiremock', ARRAY['wire mock'], 'testing'),
('assertj', ARRAY[]::TEXT[], 'testing'),
('jacoco', ARRAY[]::TEXT[], 'testing');